blank_issues_enabled: false
contact_links:
  - name: 🚑 Community support
    url: https://github.com/GsTYPO3/typo3-config-handling-extensions/discussions
    about: Please ask and answer questions here.
